apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-check
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for pod  to be Ready..."
              kubectl wait --for=condition=Ready pod/testpod --timeout=15s
