apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-check
spec:
  # ttlSecondsAfterFinished: 60
  # backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for pod  to be Ready..."
              kubectl wait --for=condition=Ready --for=condition=synced LocalNpmRepository.repository.upbound.io/testreconcile --timeout=20s
