apiVersion: repository.upbound.io/v1alpha1
kind: RemoteNpmRepository
metadata:
  name: testpostinstall
  annotations:
    crossplane.io/external-name: "testpostinstall"
spec:
  forProvider:
    description: "new remote npm repository"
    url: https://amer-write.binrepo.guidewire.net/artifactory/api/npm/testhelmpostinstall
    username: testhelmpostinstall
    passwordSecretRef:
      key: password
      name: secret-user
      namespace: testhelmpostinstall
    contentSynchronisation:
      - enabled:  true
        propertiesEnabled: true
        sourceOriginAbsenceDetection:  true
        statisticsEnabled : true
  providerConfigRef:
    name: artifactory-providerconfig-read