apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: failing-pod
  namespace: testhelmpostinstall
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/helmpostinstall
      sourceRef:
        kind: GitRepository
        name: helmpostinstall
        namespace: flux-system
  values:
    podName: broken-pod
    image: someinvalidimage:123
    checkTimeoutSeconds: 30
