apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: failing-pod
  namespace: testhelmpostinstall
spec:
  interval: 30s
  timeout: 5m
  install:
    disableWait: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./charts/
      sourceRef:
        kind: GitRepository
        name: helmpostinstall
        namespace: flux-system
  values:
    podName: broken-pod
    image: someinvalidimage:123
    checkTimeoutSeconds: 30
