apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: failing-pod
  namespace: testhelmpostinstall
spec:
  test:
    enable: true
    ignoreFailures: false
  interval: 30s
  timeout: 6m
  install:
    remediation:
      retries: -1
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/
      sourceRef:
        kind: GitRepository
        name: helmpostinstall
        namespace: testhelmpostinstall
  values:
    username: "testhelmpostinstall"
