apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: failing-pod
  namespace: testhelmpostinstall
spec:
  interval: 30s
  timeout: 2m  
  install:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/
      sourceRef:
        kind: GitRepository
        name: helmpostinstall
        namespace: flux-system
